version: '3.8'

services:
  web:
    build: .
    container_name: django_app
    command: /start
    volumes:
      - .:/app
      - ./db.sqlite3:/app/db.sqlite3
    ports:
      - "8000:8000"
    environment:
      - DEBUG=True
