# Generated by Django 5.0.6 on 2024-05-22 06:17

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_hall', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(6)])),
            ],
        ),
        migrations.CreateModel(
            name='ColumnSeats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_column', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('hall', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='columns', to='services.hall')),
            ],
        ),
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row', models.CharField(max_length=10)),
                ('number', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('available', 'Available'), ('reserved', 'Reserved'), ('booked', 'Booked')], default='available', max_length=10)),
                ('column', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seats', to='services.columnseats')),
            ],
        ),
        migrations.CreateModel(
            name='Spectacle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60)),
                ('description', models.CharField(max_length=255)),
                ('price', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('duration', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('theater_director', models.CharField(max_length=125)),
                ('hall', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='spectacles', to='services.hall')),
            ],
        ),
        migrations.CreateModel(
            name='SpectacleTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_passing', models.DateTimeField()),
                ('spectacle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='times', to='services.spectacle')),
            ],
        ),
    ]
