# Generated by Django 5.0.6 on 2024-05-22 10:41

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_spectacle_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='spectacletime',
            name='date_passing',
        ),
        migrations.AddField(
            model_name='spectacle',
            name='date_passing',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='spectacletime',
            name='time_passing',
            field=models.TimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
