# Generated by Django 5.0.6 on 2024-05-22 13:40

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_remove_spectacletime_date_passing_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='spectacle',
            name='time_passing',
            field=models.TimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='SpectacleTime',
        ),
    ]
