# Generated by Django 5.0.6 on 2024-05-23 18:26

import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0006_ticket'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='columnseats',
            options={'verbose_name': 'Column Seat', 'verbose_name_plural': 'Column Seats'},
        ),
        migrations.AlterModelOptions(
            name='hall',
            options={'verbose_name': 'Hall', 'verbose_name_plural': 'Halls'},
        ),
        migrations.AlterModelOptions(
            name='seat',
            options={'verbose_name': 'Seat', 'verbose_name_plural': 'Seats'},
        ),
        migrations.AlterModelOptions(
            name='ticket',
            options={'verbose_name': 'Ticket', 'verbose_name_plural': 'Tickets'},
        ),
        migrations.RemoveField(
            model_name='spectacle',
            name='date_passing',
        ),
        migrations.RemoveField(
            model_name='spectacle',
            name='time_passing',
        ),
        migrations.AddField(
            model_name='spectacle',
            name='datetime_passing',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='seat',
            name='status',
            field=models.CharField(choices=[('available', 'Available'), ('reserved', 'Reserved'), ('booked', 'Booked')], default='available', max_length=9),
        ),
        migrations.AlterField(
            model_name='spectacle',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterUniqueTogether(
            name='ticket',
            unique_together={('seat', 'spectacle')},
        ),
    ]
